# Generated by Django 5.0.2 on 2026-05-26 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampusForum_API', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categoria',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('OCULTO', 'Oculto'), ('BORRADOR', 'Borrador')], default='ACTIVO', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='etiquetas',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
