# Generated by Django 5.0.2 on 2026-05-26 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampusForum_API', '0004_category_alter_post_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='estado',
            field=models.CharField(choices=[('PUBLICADO', 'Publicado'), ('OCULTO', 'Oculto'), ('BORRADOR', 'Borrador')], default='PUBLICADO', max_length=20),
        ),
    ]
